### ISSUE TITLE
댓글에도 프로필사진 띄우기

### ISSUE THREAD

**Issue by NayoonBaek** [HangHae99-9-C-A/Backend#29]
댓글에도 프로필사진 띄우기
+몇 가지 수정

**Comment by NayoonBaek** [comment]
일단 급한 대로 댓글에도 if문으로 기본이미지 띄워주게 넣긴했는데 
역시 회원가입시에 기본 프로필 사진으로 넣는 게 어떤가요? 
@dnjawm19 @RefinedStone

**Comment by RefinedStone** [comment]
> 

저는 좋네요
